services:
  db:
    image: postgres:15
    container_name: qadam_database
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  redis:
    image: redis:7
    container_name: qadam_redis
    restart: always

  mq:
    image: rabbitmq:3-management
    container_name: qadam_mq
    restart: always
    env_file:
      - ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: qadam_web
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - mq

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: qadam_celery
    restart: always
    command: celery -A config worker --concurrency=2 --loglevel=INFO
    entrypoint: []
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
    env_file:
      - ./.env
    depends_on:
      - redis
      - mq
      - db
      - web

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qadam_beat
    restart: always
    command: celery -A config beat -l INFO
    entrypoint: []
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - ./.env
    depends_on:
      - redis
      - mq
      - db
      - web

volumes:
  postgres_data:
  media:
  static:
  staticfiles:
  logs:
